version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: onboarding-db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: onboarding
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
  redis:
    image: redis:latest
    container_name: myredis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  mysql_data:
