version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: onboarding-db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: onboarding
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234

volumes:
  mysql_data:
